### PR TITLE
escape hyperlink in jump_to()

### PR DESCRIPTION
**Pull request by cpsievert**
An example where this is relevant:

```r
library(rvest)
URL <- "http://www.wunderground.com/history/airport/KVAY/2015/2/17/DailyHistory.html?req_city=Cherry+Hill&req_state=NJ&req_statename=New+Jersey&reqdb.zip=08002&reqdb.magic=1&reqdb.wmo=99999&MR=1"
html_session(URL) %>% follow_link("Monthly")
```

### CODE REVIEW

**Comment by hadley** [comment]
Would you mind adding a simple unit test?

**Comment by cpsievert** [comment]
It seems as though `html_session()` doesn't work without a host. In that case, do you mind if the test request external resources? Or maybe we could use servr to serve files for testing?

**Comment by hadley** [comment]
Oh, hmmm, testing that is going to be difficult

**Comment by cpsievert** [comment]
If you don't mind adding servr to suggests I don't think it will be terribly difficult.

**Comment by cpsievert** [comment]
There is pretty nice support for a daemonized server

**Comment by hadley** [comment]
That's a lot of additional infrastructure just to test one tiny part of rvest

**Comment by hadley** [comment]
As I look at this again, I wonder - is this actually a bug in `url_absolute()`?

**Comment by hadley** [comment]
Escaping the url there is definitely wrong since it breaks the `jump_to()` example.

**Comment by hadley** [comment]
But looking at https://codecov.io/github/hadley/rvest, I'd definitely consider using servr as a way to test the session functions.

**Pull request closed without merging**
